- name: Configuring repos
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | sudo bash

- name: Configuring repos
  ansible.builtin.yum: 
      name:
        - curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | sudo bash
        - rabbitmq-server
      state: installed 

- name: Restarting Service 
  ansible.builtin.systemd:
    state: started
    name: rabbitmq-server
    enabled: yes 

- name: Adding Rabbitmq User
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: roboshop123
    permissions:
      - vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
    state: present