- name: Setting Host Name
  ansible.builtin.include_role:
    name: common
    tasks_from: sethost 
    
- name: Installing Python
  ansible.builtin.package:
    name: 
       - python36 
       - gcc 
       - python3-devel
    state: present 

- name: Creating User
  ansible.builtin.include_role:
    name: common
    tasks_from: create-user 

- name: Download and extract
  ansible.builtin.include_role:
    name: common
    tasks_from: download

- name: Cleanup old content
  ansible.builtin.file:
    path: /home/roboshop/{{COMPONENT}}
    state: absent

- name: copy file to destination 
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/roboshop/{{COMPONENT}}
    remote_src: yes
  become_user: roboshop

- name: Creating a package 
  ansible.builtin.shell: pip3 install -r requirements.txt
  args:
    chdir: /home/roboshop/{{COMPONENT}}
  become_user: roboshop





- name: Configuring Service 
  ansible.builtin.include_role:
    name: common
    tasks_from: config-service 