- name: Setting Host Name
  ansible.builtin.include_role:
    name: common
    tasks_from: sethost 
    
- name: Installing Python
  ansible.builtin.package:
    name: 
       - python36 
       - gcc 
       - python3-devel
    state: present 

- name: Creating User
  ansible.builtin.include_role:
    name: common
    tasks_from: create-user 

- name: Download and extract
  ansible.builtin.include_role:
    name: common
    tasks_from: download

- name: Cleanup old content
  ansible.builtin.file:
    path: /home/roboshop/{{COMPONENT}}
    state: absent

- name: copy file to destination 
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/roboshop/{{COMPONENT}}
    remote_src: yes
  become_user: roboshop

- name: installing dependencies 
  ansible.builtin.pip: 
      requirements: /home/roboshop/{{COMPONENT}}/requirements.txt
      executable: pip3

- name: updating User Id
  ansible.builtin.lineinfile:
    path: /home/roboshop/{{COMPONENT}}/{{COMPONENT}}.ini
    regexp: ^uid
    line: uid = {{APP_USER_INFO.uid}}     

- name: updating Group Id
  ansible.builtin.lineinfile:
    path: /home/roboshop/{{COMPONENT}}/{{COMPONENT}}.ini
    regexp: ^gid
    line: gid = {{APP_USER_INFO.group}} 

- name: Configuring Service 
  ansible.builtin.include_role:
    name: common
    tasks_from: config-service 