- name: Copying {{COMPONENT}} repo 
  ansible.builtin.copy:
     src: "{{COMPONENT}}.repo"
     dest: /etc/yum.repos.d/{{COMPONENT}}.repo 

- name: Installing {{COMPONENT}}
  ansible.builtin.package:
    name: "{{COMPONENT}}-6.2.11"
    state: present

- name: Update {{COMPONENT}} Config
  ansible.builtin.replace:
    path: /etc/{{COMPONENT}}/{{COMPONENT}}.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0' 

- name: Restarting Service 
  ansible.builtin.service:
    state: started
    name: "{{COMPONENT}}"
    enabled: yes 

- name: set hostname
  ansible.builtin.yum: set-hostname {{COMPONENT}}