frontend:
	bash components/frontend.sh;

cart:
	bash components/cart.sh;

catalogue:
	bash components/catalogue.sh;

mongodb:
	bash components/mongodb.sh;

mysql:
	bash components/mysql.sh;

payment:
	bash components/payment.sh;

redis:
	bash components/redis.sh;

user:
	bash components/user.sh;

shipping:
	bash components/shipping.sh;

rabbitmq:
	bash components/rabbitmq.sh;
