pipeline {
    agent any
    stages {
        stage ("1 stage") {
            steps{
                echo "Hello Pipeline 1"
            }
        }

        stage ("2 stage") {
            steps{
                echo "Hello Pipeline 2 "
            }
        }

        stage ("3 stage") {
            steps{
                echo "Hello Pipeline 3"
            }
        }   
    }
    
    
    
    
}