- name: Demo on using variables
  hosts: all
  vars:
     URL: play.google.com
  vars_files:
    - demovars.yml
  tasks:
     - name: printing the URL
       ansible.builtin.debug:
          msg: URL is {{URL}}

     - name: printing the URL white space
       ansible.builtin.debug:
          msg: URL is {{ URL }}

     - name: printing the URL with quotes
       ansible.builtin.debug:
          msg: "{{URL}}"  
       vars:
          URL: play.facebook.com

     - name: printing the URL with quotes
       ansible.builtin.debug:
          msg: "{{CLI_URL}}" 
       vars:
          CLI_URL: TASK_CLI.facebook.com 