- name: Demo on Privilege
  hosts: all
  become: yes
  tasks:
    - name: Running shell commands
      ansible.builtin.shell: id 
      register: OUT 

    - name: Running shell commands
      ansible.builtin.debug:
        msg: "{{OUT.stdout}}"

    - name: Running shell commands as centos
      ansible.builtin.shell: id 
      register: OUT 
      become_user: centos

    - name: Running shell commands as centos
      ansible.builtin.debug:
        msg: "{{OUT.stdout}}"
      become_user: centos

    - name: Adding User
      ansible.builtin.shell: useradd pankaj
      ignore_errors: true

    - name: Printing USER NAME
      ansible.builtin.shell: id   
      register: OUT 
      become_user: pankaj

    - name: Printing User id
      ansible.builtin.debug:
        msg: "{{OUT.stdout}}"
      



    
