- name: Copying MongoDB Repo 
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Installing MongoDB
  ansible.builtin.yum:
    name: mongodb-org
    state: installed

- name: Update MonngDB conf 
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Restaring Nginx
  ansible.builtin.service:
    name: mongod 
    state: started
    enabled: yes 

- name: Download & Extracting {{COMPONENT}}
  ansible.builtin.include_role:
    name: common 
    tasks_from: download

- name: Load Catalogue Schema
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb-main/catalogue.js"
    idempotent: yes
  loop:
    - catalogue
    - users


