- name: Check XENBUS Running??
  hosts: all
  tasks:
    - name: check XENBUS up or not
      ansible.builtin.shell: ps -ef | grep xenbus | grep -v grep
      register: out
      
    - name: starting XENBUS
      ansible.builtin.debug:
        msg: started XENBUS already
