- name: Demo on copy 
  hosts: all 
  tasks : 
    - name: Copy file to destination 
      ansible.builtin.copy:
        src: inv 
        dest: /home/centos/hosts

    - name: Copy online content to destination 
      ansible.builtin.get_url:
        url: https://github.com/b51-clouddevops/ansible/blob/main/10-demo-on-copy.yml 
        dest: /home/centos/hosts